services:
  db:
    image: mariadb:lts
    restart: always #restart everytime vm restarts
    ports: 
      - 3306:3306
    env_file: .env 
    volumes: 
      - ai-db:/var/lib/mysql

volumes:
  ai-db: